#pragma once

enum DualScalperState
{
	DS_BOTH_EMPTY,
	DS_BOTH_OPENING,
	DS_LONG_OPENING_HOLD_SHORT,
	DS_LONG_OPENING_ONLY,
	DS_SHORT_OPENING_HOLD_LONG,
	DS_SHORT_OPENING_ONLY,
	DS_HOLD_LONG,
	DS_HOLD_SHORT,
	DS_BOTH_HELD,
	DS_BOTH_CLOSING,
	DS_LONG_CLOSING_ONLY,
	DS_LONG_CLOSING_HOLD_SHORT,
	DS_SHORT_CLOSING_ONLY,
	DS_SHORT_CLOSING_HOLD_LONG,
	DS_ERROR,
};

enum DualScalperEvent
{
	EVT_OPENING,
	EVT_CLOSING,

	EVT_LONG_OPENED,
	EVT_LONG_OPEN_CANCELED,
	EVT_LONG_CLOSED,
	EVT_LONG_CLOSE_CANCELED,

	EVT_SHORT_OPENED,
	EVT_SHORT_OPEN_CANCELED,
	EVT_SHORT_CLOSED,
	EVT_SHORT_CLOSE_CANCELED
};